---
#
# tasks file for ansible-role-sshd_trusted_user_ca_setup
#
# vim:et:ts=2:ft=ansible

- name: Install public keys
  lineinfile: dest="/etc/ssh/{{ _sshd_trusted_user_ca_setup.filename }}" line='{{ item }}' insertbefore='EOF' create=yes owner=root group=root mode=0644
  with_items: "{{ _sshd_trusted_user_ca_setup.public_keys }}"
  notify:
    - Reload sshd

- name: Setup TrustedUserCAKeys in sshd_config
  lineinfile: dest="/etc/ssh/sshd_config" regexp='^TrustedUserCAKeys .*$' line='TrustedUserCAKeys /etc/ssh/{{ _sshd_trusted_user_ca_setup.filename }}' insertbefore='EOF' validate="sshd -t -f %s"
  notify:
    - Reload sshd
